
version: '3.1'

services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs
    environment: 
      SHARED_DIRECTORY: /nfsroot
    volumes:
      - /data/dockerv/nfs:/nfsroot
    ports:
      - 2049:2049
    restart: always
    privileged: true
     
