version: '3.1'

services:
  oracle:
    image: sath89/oracle-12c
    container_name: oracle
    environment:
      DBCA_TOTAL_MEMORY: 1024
    volumes:
      - ./data/oracle:/u01/app/oracle
    ports:
      - 1521:1521 
      - 18080:8080