version: '3'
services:
  es:
    image:elasticsearch:5.6.6
    container_name:es
    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./Users/huangqq/soft/docker/elasticsearch/es1/data:/usr/share/elasticsearch/data
      - ./Users/huangqq/soft/docker/elasticsearch/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - esnet