version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1 
    container_name: es
    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.type=single-node"
    volumes:
      - /data/dockerv/es:/usr/share/elasticsearch/data  
    ports:
      - 9200:9200
      - 9300:9300


