version: '2'
services:    
  kibana:
    image: kibana:5.6.6
    container_name: kibana-5.6.6
    environment:
        - ELASTICSEARCH_URL=http://172.20.0.1:9200
    ports:
      - 5601:5601   
    networks:
      - esnet  
      
networks:
  esnet: