version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /data/dockerv/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart:
      always 
