kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keda
  namespace: dolphin
  annotations:
    volume.beta.kubernetes.io/storage-class: "kube-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
