version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.9
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper/conf:/opt/zookeeper-3.4.9  
      - ./data/zookeeper/data:/kafka  
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.75.2
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./data/kafka/var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka
