version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.13
    ports:
      - "2181:2181"
    volumes:
      - /data/dockerv/kafka/zookeeper/logs:/logs
      - /data/dockerv/kafka/zookeeper/data:/data  
      - /data/dockerv/kafka/zookeeper/datalog:/datalog  
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.56.101
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:

      - /data/dockerv/kafka:/kafka
